version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - .:/work
    environment:
      SWAGGER_JSON: /work/schema/openapi.yml
    restart: always
