version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./schema/openapi.yml:/openapi.yml
      - ./schema/paths:/paths
      - ./schema/types:/types
    environment:
      SWAGGER_JSON: /openapi.yml
    restart: always
