openapi: 3.0.0

info:
  title: SeichiAPISchema
  description: 整地鯖のAPIのドキュメントをまとめるOpenAPIサーバー
  version: 1.0.0

servers:
  - url: 'http://localhost:9000/'
    description: seichi-portal-backend(開発環境)

paths:
  /api/forms/create:
    $ref: './paths/forms/create.yaml'
  /api/forms:
    $ref: './paths/forms/list.yaml'
