name: Lint OpenAPI
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/redocly-cli
        with:
          command-args: lint /spec/schema/openapi.yml
