name: Lint OpenAPI files
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install -g redoc-cli
      - name: Bundle
        run: redoc-cli bundle schema/openapi.yml --output bundled.yml
      - name: Lint
        run: redoc-cli lint bundled.yaml
