name: Lint OpenAPI files
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bundle
        run: docker run --rm -v $PWD:/spec redocly/cli bundle /spec/schema/openapi.yml --output /spec/bundled.yml
      - name: Check files
        run: ls | grep yml
