name: Lint OpenAPI
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install redocly-cli
        uses: ./.github/actions/install-redocly-cli
      - name: Lint OpenAPI yml
        run: lint ./schema/openapi.yml
  lint-examples:
    name: Lint examples of OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install redocly-cli
        uses: ./.github/actions/install-redocly-cli
      - name: Bundle OpenAPI yml
        run: bundle ./schema/openapi.yml -o ./schema/bundled-openapi.yml
      - name: Install openapi-examples-validator
        run: npm install -g openapi-examples-validator
      - name: Lint examples
        run: openapi-examples-validator ./bundled-openapi.yml
